[package]
name = "rust2go-cli"
version = "0.2.0"

description = "Rust2go commandline tool."

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
cbindgen = "0.26"
rust2go-common = { version = "0.2.0", path = "../rust2go-common" }

[[bin]]
name = "rust2go-cli"
path = "src/main.rs"
